apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ${STATEFUL_SET}
  namespace: ${NAMESPACE}
spec:
  serviceName: ${SERVICE}
  selector:
    matchLabels:
      service: ${SERVICE}
  template:
    metadata:
      labels:
        service: ${SERVICE}
    spec:
      runtimeClassName: gvisor
      nodeSelector:
        cloud.google.com/gke-nodepool: apps

      volumes:
      - name: ${SERVICE_VOLUME}
        persistentVolumeClaim:
          claimName: ${SERVICE_VOLUME}

      containers:
      - name: codedx
        image: ${CODEDX_IMAGE}
        command: ['sh', '-c']
        args:
        - rm -f
            /opt/codedx/codedx.props \
            /opt/codedx/logback.xml &&
          start.sh
        env:
        - name: DB_URL
          value: jdbc:mysql://localhost/${DB_NAME}
        - name: DB_DRIVER
          value: com.mysql.jdbc.Driver
        - name: DB_USER
          value: ${DB_USER}
        - name: SUPERUSER_NAME
          value: admin
        - name: JAVA_OPTS
          value: -Xmx8000M
        envFrom:
        - secretRef:
            name: ${SERVICE_SECRET}
        ports:
        - name: ${TARGET_PORT}
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /codedx/classpath/login-page.js
            port: ${TARGET_PORT}
          timeoutSeconds: 10
          initialDelaySeconds: 360
        volumeMounts:
        - name: ${SERVICE_VOLUME}
          mountPath: /opt/codedx
        resources:
          requests:
            memory: 10000M

      - name: codedx-db
        image: mariadb:10.3
        imagePullPolicy: Always
        args:
        - --optimizer_search_depth=0
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_general_ci
        - --lower_case_table_names=1
        env:
        - name: MYSQL_DATABASE
          value: ${DB_NAME}
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ${SERVICE_SECRET}
              key: DB_ROOT_PASSWORD
        - name: MYSQL_USER
          value: ${DB_USER}
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ${SERVICE_SECRET}
              key: DB_PASSWORD
        volumeMounts:
        - name: ${SERVICE_VOLUME}
          mountPath: /var/lib/mysql
          subPath: mariadb
        resources:
          requests:
            memory: 1500M
