options:
  env:
  - terraform_bucket=${PROJECT_ID}-terraform
  - defectdojo_image=gcr.io/${PROJECT_ID}/defectdojo-django

steps:
# prepare GCS backend for Terraform
- id: terraform-bucket
  name: gcr.io/cloud-builders/gsutil
  entrypoint: sh
  args:
  - -c
  - gsutil mb gs://${terraform_bucket} &&
    gsutil versioning set on gs://${terraform_bucket} || true

# deploy GKE cluster and associated GCP resources
- id: terraform
  name: hashicorp/terraform
  entrypoint: sh
  dir: cluster
  args:
  - -c
  - terraform init --backend-config="bucket=${terraform_bucket}" &&
    terraform plan --out=plan.out -var="project=${PROJECT_ID}" &&
    terraform apply plan.out &&
    terraform output | tr -d " " > output.sh

# set up Config Connector and other shared GKE resources
- id: cluster
  name: gcr.io/cloud-builders/gcloud
  entrypoint: sh
  dir: cluster
  args:
  - -c
  - |
    set -eu

    . ./output.sh
    gcloud container clusters get-credentials --zone "${zone}" "${cluster}"

    ./cnrm.sh "${cnrm_sa}"
    kubectl apply -f .

# build a common SDK image that provides kubectl and envsubst commands
- id: kubectl-sdk
  name: gcr.io/kaniko-project/executor:debug-a1af057f997316bfb1c4d2d82719d78481a02a79
  waitFor: ['-']
  args:
  - --destination=gcr.io/${PROJECT_ID}/kubectl-sdk
  - --context=dir:///workspace/kubectl-sdk
  - --cache=true

# build patched DefectDojo image
# (can't use Kaniko due to https://github.com/GoogleContainerTools/kaniko/issues/477)
- id: defectdojo-docker
  name: gcr.io/cloud-builders/docker
  waitFor: ['-']
  entrypoint: sh
  dir: defectdojo
  args:
  - -c
  - docker build -t ${defectdojo_image} . &&
    docker push -t ${defectdojo_image}
