options:
  env:
  - terraform_bucket=${PROJECT_ID}-terraform

steps:
- name: gcr.io/cloud-builders/gsutil
  entrypoint: sh
  args:
  - -c
  - gsutil mb gs://${terraform_bucket} &&
    gsutil versioning set on gs://${terraform_bucket} || true

- name: hashicorp/terraform
  entrypoint: sh
  dir: cluster
  args:
  - -c
  - terraform init --backend-config="bucket=${terraform_bucket}" &&
    terraform plan --out=plan.out -var="project=${PROJECT_ID}" &&
    terraform apply plan.out &&
    terraform output | tr -d " " > output.sh

- name: gcr.io/cloud-builders/gcloud
  entrypoint: sh
  dir: cluster
  args:
  - -c
  - |
    set -eu

    . ./output.sh
    gcloud container clusters get-credentials --zone "${zone}" "${cluster}"

    ./cnrm.sh "${PROJECT_ID}" "${cnrm_sa}"
    kubectl apply -f deploy.yaml
