substitutions:
  _CARTOGRAPHY_SERVICE_ACCOUNT: '' # replace in Cloud Build UI

options:
  env:
  - PROJECT_ID=${PROJECT_ID}
  - BATCH_DISPATCHER_IMAGE=us.gcr.io/${PROJECT_ID}/batch-dispatcher
  - BASTION_IMAGE=us.gcr.io/${PROJECT_ID}/bastion
  - CIS_IMAGE=us.gcr.io/${PROJECT_ID}/cis
  - DD_DJANGO_IMAGE=us.gcr.io/${PROJECT_ID}/defectdojo-django
  - DD_NGINX_IMAGE=us.gcr.io/${PROJECT_ID}/defectdojo-nginx
  - CODEDX_IMAGE=us.gcr.io/${PROJECT_ID}/codedx
  - SDARQ_FRONTEND_IMAGE=us.gcr.io/${PROJECT_ID}/sdarq-frontend:${SHORT_SHA}
  - SDARQ_BACKEND_IMAGE=us.gcr.io/${PROJECT_ID}/sdarq-backend:${SHORT_SHA}
  - CARTOGRAPHY_IMAGE=us.gcr.io/${PROJECT_ID}/cartography
  - DNS_DOMAIN=dsp-appsec.broadinstitute.org
  - DNS_ZONE=dsp-appsec
  - TERRAFORM_BUCKET=${PROJECT_ID}-terraform
  - BROAD_INGRESS_CSP=broad-ingress
  - DISK_SNAPSHOT_POLICY=appsec-apps-disk-snapshot-policy
  - JOB_CREATOR_ROLE=job-creator
  - GLOBAL_NAMESPACE=global
  - CIS_NAMESPACE=cis
  - CIS_DATASET=cis
  - DOJO_NAMESPACE=defectdojo
  - DOJO_SERVICE=defectdojo
  - REGION=us-east1
  - ZONE_1=us-east1-b
  - ZONE_2=us-east1-c

steps:
# prepare GCS backend for Terraform
- id: terraform-bucket
  name: gcr.io/cloud-builders/gsutil
  entrypoint: sh
  args:
  - -c
  - gsutil mb "gs://$${TERRAFORM_BUCKET}" &&
    gsutil versioning set on "gs://$${TERRAFORM_BUCKET}" || true

# build bastion proxy Docker image,
# using Kaniko to speed up builds
- id: bastion-image
  name: &kaniko gcr.io/kaniko-project/executor:debug
  waitFor: ['-']
  entrypoint: sh
  args:
  - -c
  - executor
      --context=dir:///workspace/bastion
      --destination=$${BASTION_IMAGE}
      --cache

# deploy GKE cluster and associated GCP resources
- id: terraform
  name: hashicorp/terraform
  waitFor: ['terraform-bucket', 'bastion-image']
  entrypoint: sh
  dir: terraform
  args:
  - -c
  - terraform init
      -backend-config "bucket=$${TERRAFORM_BUCKET}" &&
    terraform plan -out=plan.out
      -var "project=${PROJECT_ID}"
      -var "region=$${REGION}"
      -var "zones=[\"$${ZONE_1}\",\"$${ZONE_2}\"]"
      -var "bastion_image=$${BASTION_IMAGE}" &&
    terraform apply plan.out &&
    terraform output | tr -d " " > ../.env

# set up Config Connector and other shared GKE resources
- id: shared
  name: &kubectl gcr.io/cloud-builders/kubectl
  entrypoint: sh
  dir: shared
  args:
  - -c
  - export $(xargs < ../.env) && ./global.sh

# build CIS Docker image
- id: cis-image
  name: *kaniko
  waitFor: ['-']
  entrypoint: sh
  args:
  - -c
  - executor
      --context=dir:///workspace/cis
      --destination=$${CIS_IMAGE}
      --cache

# deploy CIS scanner resources
- id: cis
  name: *kubectl
  waitFor: ['shared', 'cis-image']
  entrypoint: ./deploy.sh
  dir: cis

# build patched DefectDojo Django image,
# using Kaniko to speed up builds
- id: defectdojo-django-image
  name: *kaniko
  waitFor: ['-']
  entrypoint: sh
  args:
  - -c
  - executor
      --context=dir:///workspace/defectdojo
      --dockerfile=Dockerfile.django
      --destination=$${DD_DJANGO_IMAGE}
      --cache

# build patched DefectDojo Nginx image
- id: defectdojo-nginx-image
  name: *kaniko
  waitFor: ['-']
  entrypoint: sh
  args:
  - -c
  - executor
      --context=dir:///workspace/defectdojo
      --dockerfile=Dockerfile.nginx
      --destination=$${DD_NGINX_IMAGE}
      --cache

# deploy DefectDojo to GKE cluster
- id: defectdojo
  name: *kubectl
  waitFor: ['shared', 'defectdojo-django-image', 'defectdojo-nginx-image']
  entrypoint: ./deploy.sh
  dir: defectdojo


# build patched CodeDx image
- id: codedx-image
  name: *kaniko
  waitFor: ['-']
  entrypoint: sh
  args:
  - -c
  - executor
      --context=dir:///workspace/codedx
      --destination=$${CODEDX_IMAGE}
      --cache

# deploy CodeDx to GKE cluster
- id: codedx
  name: *kubectl
  waitFor: ['shared', 'codedx-image']
  entrypoint: ./deploy.sh
  dir: codedx

# build SDARQ frontend Docker image
- id: sdarq-frontend-image
  name: *kaniko
  waitFor: ['-']
  entrypoint: sh
  args:
  - -c
  - executor
      --context=dir:///workspace/sdarq/frontend
      --destination=$${SDARQ_FRONTEND_IMAGE}
      --cache

# build SDARQ backend Docker image
- id: sdarq-backend-image
  name: *kaniko
  waitFor: ['-']
  entrypoint: sh
  args:
  - -c
  - executor
      --context=dir:///workspace/sdarq/backend
      --destination=$${SDARQ_BACKEND_IMAGE}
      --cache

# deploy SDARQ to GKE cluster
- id: sdarq
  name: *kubectl
  waitFor: ['shared', 'sdarq-frontend-image', 'sdarq-backend-image', 'cis']
  entrypoint: ./deploy.sh
  dir: sdarq

# build Cartography Docker image
- id: cartography-image
  name: *kaniko
  waitFor: ['-']
  entrypoint: sh
  args:
  - -c
  - executor
      --context=dir:///workspace/secexplorer
      --destination=$${CARTOGRAPHY_IMAGE}
      --cache

# deploy SecExplorer to GKE cluster
- id: secexplorer
  name: *kubectl
  waitFor: ['shared', 'cartography-image']
  entrypoint: ./deploy.sh
  dir: secexplorer
  env:
  - GCP_SERVICE_ACCOUNT_EMAIL=${_CARTOGRAPHY_SERVICE_ACCOUNT}

# build Batch dispatcher image
- id: batch-dispatcher-image
  name: *kaniko
  waitFor: ['-']
  entrypoint: sh
  args:
  - -c
  - executor
      --context=dir:///workspace/batch
      --destination=$${BATCH_DISPATCHER_IMAGE}
      --cache

timeout: 7200s
