options:
  env:
  - DD_DJANGO_IMAGE=us.gcr.io/${PROJECT_ID}/defectdojo-django
  - DD_NGINX_IMAGE=us.gcr.io/${PROJECT_ID}/defectdojo-nginx
  - CODEDX_IMAGE=us.gcr.io/${PROJECT_ID}/codedx
  - SDARQ_FRONTEND_IMAGE=us.gcr.io/${PROJECT_ID}/sdarq-frontend
  - SDARQ_BACKEND_IMAGE=us.gcr.io/${PROJECT_ID}/sdarq-backend
  - DNS_DOMAIN=dsp-appsec.broadinstitute.org
  - DNS_ZONE=dsp-appsec
  - TERRAFORM_BUCKET=${PROJECT_ID}-terraform
  - BROAD_INGRESS_CSP=broad-ingress
  - DISK_SNAPSHOT_POLICY=appsec-apps-disk-snapshot-policy
  - GLOBAL_NAMESPACE=global
  - REGION=us-east1
  - ZONE_1=us-east1-b
  - ZONE_2=us-east1-c

steps:
# prepare GCS backend for Terraform
- id: terraform-bucket
  name: gcr.io/cloud-builders/gsutil
  entrypoint: sh
  args:
  - -c
  - gsutil mb "gs://$${TERRAFORM_BUCKET}" &&
    gsutil versioning set on "gs://$${TERRAFORM_BUCKET}" || true

# deploy GKE cluster and associated GCP resources
- id: terraform
  name: hashicorp/terraform
  entrypoint: sh
  dir: terraform
  args:
  - -c
  - terraform init
      -backend-config="bucket=$${TERRAFORM_BUCKET}" &&
    terraform plan -out=plan.out
      -var="project=${PROJECT_ID}"
      -var="region=$${REGION}"
      -var="zones=[\"$${ZONE_1}\",\"$${ZONE_2}\"]" &&
    terraform apply plan.out &&
    terraform output | tr -d " " > ../.env

# set up Config Connector and other shared GKE resources
- id: shared
  name: &kubectl gcr.io/cloud-builders/kubectl
  entrypoint: sh
  dir: shared
  args:
  - -c
  - export $(xargs < ../.env) && ./global.sh

# build patched DefectDojo Django image
# using Kaniko to speed up builds
- id: defectdojo-django
  name: &kaniko gcr.io/kaniko-project/executor:debug
  waitFor: ['-']
  entrypoint: sh
  args:
  - -c
  - executor
      --context=dir:///workspace/defectdojo
      --dockerfile=Dockerfile.django
      --destination=$${DD_DJANGO_IMAGE}
      --cache

# build patched DefectDojo Nginx image
- id: defectdojo-nginx
  name: *kaniko
  waitFor: ['-']
  entrypoint: sh
  args:
  - -c
  - executor
      --context=dir:///workspace/defectdojo
      --dockerfile=Dockerfile.nginx
      --destination=$${DD_NGINX_IMAGE}
      --cache

# deploy DefectDojo to GKE cluster
- id: defectdojo
  name: *kubectl
  waitFor: ['shared', 'defectdojo-django', 'defectdojo-nginx']
  entrypoint: ./deploy.sh
  dir: defectdojo


# build patched CodeDx image
- id: codedx-docker
  name: *kaniko
  waitFor: ['-']
  entrypoint: sh
  args:
  - -c
  - executor
      --context=dir:///workspace/codedx
      --destination=$${CODEDX_IMAGE}
      --cache

# deploy CodeDx to GKE cluster
- id: codedx
  name: *kubectl
  waitFor: ['shared', 'codedx-docker']
  entrypoint: ./deploy.sh
  dir: codedx

# build SDARQ frontend Docker image
- id: sdarq-frontend
  name: *kaniko
  waitFor: ['-']
  entrypoint: sh
  args:
  - -c
  - executor
      --context=dir:///workspace/sdarq/frontend
      --destination=$${SDARQ_FRONTEND_IMAGE}
      --cache

# build SDARQ backend Docker image
- id: sdarq-backend
  name: *kaniko
  waitFor: ['-']
  entrypoint: sh
  args:
  - -c
  - executor
      --context=dir:///workspace/sdarq/backend
      --destination=$${SDARQ_BACKEND_IMAGE}
      --cache

# deploy SDARQ to GKE cluster
- id: sdarq
  name: *kubectl
  waitFor: ['shared', 'sdarq-frontend', 'sdarq-backend']
  entrypoint: ./deploy.sh
  dir: sdarq

timeout: 3600s
