---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${JOB_CONFIG_MAP}
  namespace: ${NAMESPACE}
data:
  spec: |
    ttlSecondsAfterFinished: 0
    template:
      spec:
        serviceAccountName: ${K8S_SERVICE_ACCOUNT}
        #runtimeClassName: gvisor
        restartPolicy: OnFailure
        nodeSelector:
          cloud.google.com/gke-nodepool: batch
        tolerations:
        - key: sandbox.gke.io/runtime
          operator: Equal
          value: gvisor
          effect: NoSchedule

        containers:
        - name: cis-scan
          image: ${CIS_IMAGE}
          env:
          - name: BQ_DATASET
            value: ${CIS_DATASET}
          - name: GCP_PROJECT_ID
            value: {JOB_INPUT}
          resources:
            requests:
              memory: 250M
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${K8S_SERVICE_ACCOUNT}
  namespace: ${NAMESPACE}
  annotations:
    iam.gke.io/gcp-service-account: ${GCP_SERVICE_ACCOUNT_EMAIL}
---
apiVersion: bigquery.cnrm.cloud.google.com/v1beta1
kind: BigQueryDataset
metadata:
  name: ${CIS_DATASET}
  namespace: ${NAMESPACE}
  annotations:
    cnrm.cloud.google.com/deletion-policy: abandon
spec:
  description: "CIS scan results"
  access:
  - role: OWNER
    specialGroup: projectOwners
  - role: WRITER
    userByEmail: ${GCP_SERVICE_ACCOUNT_EMAIL}
  - role: WRITER
    userByEmail: ${SDARQ_SERVICE_ACCOUNT}@${PROJECT_ID}.iam.gserviceaccount.com
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: ${K8S_SERVICE_ACCOUNT}-sa-bq-policy
  namespace: ${NAMESPACE}
spec:
  member: serviceAccount:${GCP_SERVICE_ACCOUNT_EMAIL}
  role: roles/bigquery.jobUser
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: projects/${PROJECT_ID}
