---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${JOB_CONFIG_MAP}
  namespace: ${NAMESPACE}
data:
  spec: |
    template:
      spec:
        serviceAccountName: ${JOB_SERVICE_ACCOUNT}
        #runtimeClassName: gvisor
        restartPolicy: OnFailure
        nodeSelector:
          cloud.google.com/gke-nodepool: batch
        tolerations:
        - key: sandbox.gke.io/runtime
          operator: Equal
          value: gvisor
          effect: NoSchedule

        containers:
        - name: cis-azure-scans
          image: ${CIS_AZURE_SCANS}
          imagePullPolicy: Always
          env:
          - name: SLACK_TOKEN
            valueFrom:
              secretKeyRef:
                 name: ${JOB_SECRET}
                 key: SLACK_TOKEN
          - name: SLACK_CHANNEL
            valueFrom:
              fieldRef:
                fieldPath: metadata.annotations['SLACK_CHANNEL']
          resources:
            requests:
              memory: 2Gi
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cis-azure-trigger-weekly
  namespace: ${NAMESPACE}
spec:
  schedule: "0 7 * * 4"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: ${CRON_SERVICE_ACCOUNT}
          runtimeClassName: gvisor
          nodeSelector:
            cloud.google.com/gke-nodepool: batch
          restartPolicy: OnFailure

          containers:
          - name: cis-azure-scans
            image: ${CIS_AZURE_SCANS}
            command: ['python3', '/entrypoint.py']
            env:
              - name: SLACK_CHANNEL
                valueFrom:
                  secretKeyRef:
                    name: ${JOB_SECRET}
                    key: SLACK_CHANNEL

