---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${JOB_CONFIG_MAP}
  namespace: ${NAMESPACE}
data:
  spec: |
    template:
      spec:
        runtimeClassName: gvisor
        nodeSelector:
          cloud.google.com/gke-nodepool: batch
        restartPolicy: OnFailure
        containers:
          - name: CONTAINER_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['CONTAINER_NAME']
            image: ${SOURCECLEAR_IMAGE}
            imagePullPolicy: Always
            cmd: ["./scan.sh"]
            env:
            - name: PROJECT
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['PROJECT']
            - name: BRANCH
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['BRANCH']
            - name: REPO
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['REPO']
            - name: WORKSPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['WORKSPACE']
            - name: ORG
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['ORG']
            - name: SCAN_SUBDIR
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['SUBDIR']
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: sourceclear-pubsub
  namespace: ${NAMESPACE}
  labels:
    jobgroup: weekly-sourceclear-scans
spec:
  schedule: "0 0 * * 0"
  jobTemplate:
    spec:
      template:
        metadata:
            name: weekly-sourceclear-scans
            labels:
                jobgroup: weekly-sourceclear-scans
        spec:
            runtimeClassName: gvisor
            nodeSelector:
              cloud.google.com/gke-nodepool: batch
            containers:
            - name: {{ name }}-pub
              image: ${SOURCECLEAR_IMAGE}
              command: ["./publish"]
            restartPolicy: OnFailure
      backoffLimit: 3