---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name:  ${SERVICE}
  namespace: ${NAMESPACE}
spec:
  schedule: "0 1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: ${SERVICE_ACCOUNT}
          runtimeClassName: gvisor
          nodeSelector:
            cloud.google.com/gke-nodepool: batch
          restartPolicy: OnFailure

          containers:
          - name: security-controls
            image: ${SDARQ_SECURITY_CONTROLS}
            command: ['python3', '/entrypoint.py']
            envFrom:
            - secretRef:
                name: ${SERVICE_SECRET}
            env:
              - name: DEFECT_DOJO_URL
                value: ${DEFECT_DOJO_URL}
