---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${JOB_DEPLOYMENT}
  namespace: ${NAMESPACE}
spec:
  selector:
    matchLabels:
      deployment: ${JOB_DEPLOYMENT}
  template:
    metadata:
      labels:
        deployment: ${JOB_DEPLOYMENT}
    spec:
      serviceAccountName: ${SERVICE_ACCOUNT}
      nodeSelector:
        cloud.google.com/gke-nodepool: apps
      containers:
      - name: codedx-analysis
        image: ${CODEDX_ANALYSIS_IMAGE}
        envFrom:
          - secretRef:
              name: ${CODEDX_ANALYSIS_SECRET}
        env:
          - name: SUBSCRIPTION
            value: ${JOB_SUBSCRIPTION}
          - name: CODEDX_URL
            value: ${CODEDX_URL}
          - name: PROJECT_ID
            value: ${PROJECT_ID}
        resources:
          requests:
            memory: 65M
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: ${SERVICE_ACCOUNT}-sa-pubsub-policy
  namespace: ${NAMESPACE}
spec:
  member: serviceAccount:${SERVICE_ACCOUNT}@${PROJECT_ID}.iam.gserviceaccount.com
  role: roles/pubsub.subscriber
  resourceRef:
    apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
    kind: PubSubSubscription
    name: ${JOB_SUBSCRIPTION}
---
apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubTopic
metadata:
  name: ${JOB_TOPIC}
  namespace: ${NAMESPACE}
---
apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubSubscription
metadata:
  name: ${JOB_SUBSCRIPTION}
  namespace: ${NAMESPACE}
spec:
  topicRef:
    name: ${JOB_TOPIC}
---
apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucket
metadata:
  name: ${BUCKET_NAME}
  namespace: ${NAMESPACE}
---
apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageNotification
metadata:
  name: ${BUCKET_NOTIFICATION}
  namespace: ${NAMESPACE}
spec:
  bucketRef:
    name: ${BUCKET_NAME}
  payloadFormat: JSON_API_V1
  topicRef:
    name: ${JOB_TOPIC}
  eventTypes:
    - "OBJECT_FINALIZE"
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: ${BUCKET_SA_IAM_POLICY}
  namespace: ${NAMESPACE}
spec:
  member: serviceAccount:${SERVICE_ACCOUNT}@${PROJECT_ID}.iam.gserviceaccount.com
  role: roles/storage.reader
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: StorageBucket
    name: ${BUCKET_NAME}
