---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${JOB_DEPLOYMENT}
  namespace: ${NAMESPACE}
spec:
  selector:
    matchLabels:
      deployment: ${JOB_DEPLOYMENT}
  template:
    metadata:
      labels:
        deployment: ${JOB_DEPLOYMENT}
    spec:
      serviceAccountName: ${SERVICE_ACCOUNT}
      runtimeClassName: gvisor
      nodeSelector:
        cloud.google.com/gke-nodepool: apps
      containers:
      - name: codedx-analysis
        image: ${CODEDX_ANALYSIS_IMAGE}
        envFrom:
          - secretRef:
              name: ${CODEDX_ANALYSIS_SECRET}
        env:
          - name: SUBSCRIPTION
            value: ${JOB_SUBSCRIPTION}
          - name: CODEDX_URL
            value: ${CODEDX_URL}
          - name: PROJECT_ID
            value: ${PROJECT_ID}
        resources:
          requests:
            memory: 65M
---
apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubTopic
metadata:
  name: ${JOB_TOPIC}
  namespace: ${NAMESPACE}
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: ${JOB_TOPIC}-publisher-policy
  namespace: ${NAMESPACE}
spec:
  member: serviceAccount:service-${PROJECT_NUMBER}@gs-project-accounts.iam.gserviceaccount.com
  role: roles/pubsub.publisher
  resourceRef:
    apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
    kind: PubSubTopic
    name: ${JOB_TOPIC}
---
apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubSubscription
metadata:
  name: ${JOB_SUBSCRIPTION}
  namespace: ${NAMESPACE}
spec:
  ackDeadlineSeconds: 30
  topicRef:
    name: ${JOB_TOPIC}
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: ${JOB_SUBSCRIPTION}-editor-policy
  namespace: ${NAMESPACE}
spec:
  member: serviceAccount:${SERVICE_ACCOUNT}@${PROJECT_ID}.iam.gserviceaccount.com
  role: roles/pubsub.editor
  resourceRef:
    apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
    kind: PubSubSubscription
    name: ${JOB_SUBSCRIPTION}
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: ${JOB_SUBSCRIPTION}-subscriber-policy
  namespace: ${NAMESPACE}
spec:
  member: serviceAccount:${SERVICE_ACCOUNT}@${PROJECT_ID}.iam.gserviceaccount.com
  role: roles/pubsub.subscriber
  resourceRef:
    apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
    kind: PubSubSubscription
    name: ${JOB_SUBSCRIPTION}
---
apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucket
metadata:
  name: ${BUCKET_NAME}
  namespace: ${NAMESPACE}
  annotations:
    cnrm.cloud.google.com/deletion-policy: abandon
---
apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageNotification
metadata:
  name: ${BUCKET_NOTIFICATION}
spec:
  bucketRef:
    name: ${BUCKET_NAME}
  payloadFormat: JSON_API_V1
  topicRef:
    external: "//pubsub.googleapis.com/projects/${PROJECT_ID}/topics/${JOB_TOPIC}"
  eventTypes:
    - "OBJECT_FINALIZE"
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: ${BUCKET_NAME}-policy
  namespace: ${NAMESPACE}
spec:
  member: serviceAccount:${SERVICE_ACCOUNT}@${PROJECT_ID}.iam.gserviceaccount.com
  role: roles/storage.objectViewer
  resourceRef:
    apiVersion: storage.cnrm.cloud.google.com/v1beta1
    kind: StorageBucket
    name: ${BUCKET_NAME}
