---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${JOB_DEPLOYMENT}
  namespace: ${NAMESPACE}
spec:
  selector:
    matchLabels:
      deployment: ${JOB_DEPLOYMENT}
  template:
    metadata:
      labels:
        deployment: ${JOB_DEPLOYMENT}
    spec:
      serviceAccountName: ${SERVICE_ACCOUNT}
      nodeSelector:
        cloud.google.com/gke-nodepool: system
      containers:
      - name: job-dispatcher
        image: ${CODEDX_ANALYSIS_IMAGE}
        env:
        - name: PROJECT_ID
          value: ${PROJECT_ID}
        - name: SUBSCRIPTION
          value: ${JOB_SUBSCRIPTION}
        - name: CODEDX_URL
          value: ${CODEDX_URL} 
        - name: SECRET_NAME
          value: ${NAMESPACE}  
        - name: SECRET_NAME
          value: ${SECRET_NAME}
        - name: SECRET_VERSION
          value: ${SECRET_VERSION}
        - name: SPEC_PATH
          value: ${JOB_CONFIG_MOUNT_PATH}/${JOB_SPEC_KEY}
        volumeMounts:
        - name: ${JOB_CONFIG_VOLUME}
          mountPath: ${JOB_CONFIG_MOUNT_PATH}
        resources:
          requests:
            memory: 65M
      volumes:
      - name: ${JOB_CONFIG_VOLUME}
        configMap:
          name: ${JOB_CONFIG_MAP}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ${SERVICE_ACCOUNT}
  namespace: ${NAMESPACE}
subjects:
- kind: ServiceAccount
  name: ${SERVICE_ACCOUNT}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ${JOB_DISPATCHER_ROLE}
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: ${SERVICE_ACCOUNT}-sa-pubsub-policy
  namespace: ${NAMESPACE}
spec:
  member: serviceAccount:${SERVICE_ACCOUNT}@${PROJECT_ID}.iam.gserviceaccount.com
  role: roles/pubsub.subscriber
  resourceRef:
    apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
    kind: PubSubSubscription
    name: ${JOB_SUBSCRIPTION}
---
apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubTopic
metadata:
  name: ${JOB_TOPIC}
  namespace: ${NAMESPACE}
---
apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubSubscription
metadata:
  name: ${JOB_SUBSCRIPTION}
  namespace: ${NAMESPACE}
spec:
  topicRef:
    name: ${JOB_TOPIC}
---
apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucket
metadata:
  name: ${BUCKET_NAME}
  namespace: ${NAMESPACE}
---
apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageNotification
metadata:
  name: ${BUCKET_NOTIFICATION}
  namespace: ${NAMESPACE}
spec:
  bucketRef:
    name: ${BUCKET_NAME}
  payloadFormat: JSON_API_V1
  topicRef:
    name: ${JOB_TOPIC}
  eventTypes:
    - "OBJECT_FINALIZE"
---
apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucketAccessControl
metadata:
  name: ${BUCKET_ACCESS}
spec:
  bucketRef:
    name: ${BUCKET_NAME}
  entity: ${BUCKET_ACCESS_ENTITY}
  role: EDITOR
---
apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucketAccessControl
metadata:
  name: ${BUCKET_ACCESS}-sa
spec:
  bucketRef:
    name: ${BUCKET_NAME}
  entity: ${SERVICE_ACCOUNT}
  role: READER