apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSecurityPolicy
metadata:
  name: broad-ingress
spec:
  rule:
  - action: allow
    priority: 1
    match:
      versionedExpr: SRC_IPS_V1
      config:
        srcIpRanges:
        - 69.173.112.0/21
        - 69.173.127.232/29
        - 69.173.127.128/26
        - 69.173.127.0/25
        - 69.173.127.240/28
  - action: allow
    priority: 2
    match:
      versionedExpr: SRC_IPS_V1
      config:
        srcIpRanges:
        - 69.173.127.224/30
        - 69.173.127.230/31
        - 69.173.120.0/22
        - 69.173.127.228/32
        - 69.173.126.0/24
  - action: allow
    priority: 3
    match:
      versionedExpr: SRC_IPS_V1
      config:
        srcIpRanges:
        - 69.173.96.0/20
        - 69.173.64.0/19
        - 69.173.127.192/27
        - 69.173.124.0/23
  - action: deny(403)
    priority: 2147483647
    match:
      versionedExpr: SRC_IPS_V1
      config:
        srcIpRanges:
        - '*'
---
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: broad-ingress
spec:
  securityPolicy:
    name: broad-ingress
