---
    apiVersion: batch/v1beta1
    kind: CronJob
    metadata:
      name: automated-cis-scan-cronjob
      namespace: ${NAMESPACE}
      labels:
        jobgroup: aautomated-cis-scan
    spec:
      schedule: "0 0 * * 0"
      jobTemplate:
        spec:
          template:
            metadata:
              name: automated-cis-scan
              labels:
                  jobgroup: automated-cis-scan
            spec:
              runtimeClassName: gvisor
              nodeSelector:
                cloud.google.com/gke-nodepool: batch
              restartPolicy: OnFailure
              containers:
              - name: automated-cis-scan
                image: ${AUTOMATED_CIS_SCAN_IMAGE}
                command: ['python3 scanweekly.py']
                env:
                  - name: BQ_DATASET
                    valueFrom:
                      secretKeyRef:
                        name: ${NAMESPACE}
                        key: BQ_DATASET
                  - name: SLACK_TOKEN
                    valueFrom:
                      secretKeyRef:
                         name: ${NAMESPACE}
                         key: SLACK_TOKEN
                  - name: SLACK_CHANNEL
                    valueFrom:
                      secretKeyRef:
                        name: ${NAMESPACE}
                        key: SLACK_CHANNEL
                  - name: GCP_PROJECT_ID
                    valueFrom:
                      secretKeyRef:
                        name: ${NAMESPACE}
                        key: GCP_PROJECT_ID
                  - name: TOPIC_NAME
                    valueFrom:
                      secretKeyRef:
                        name: ${NAMESPACE}
                        key: TOPIC_NAME
---
  apiVersion: iam.cnrm.cloud.google.com/v1beta1
  kind: IAMPolicyMember
  metadata:
    name: ${SERVICE_ACCOUNT}-bq-job-policy
    namespace: ${NAMESPACE}
  spec:
    member: serviceAccount:${SERVICE_ACCOUNT}@${PROJECT_ID}.iam.gserviceaccount.com
    role: roles/bigquery.jobUser
    resourceRef:
      apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
      kind: Project
      external: projects/${PROJECT_ID}
