apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ${STATEFUL_SET}
  namespace: ${NAMESPACE}
spec:
  serviceName: ${SERVICE}
  selector:
    matchLabels:
      service: ${SERVICE}
  template:
    metadata:
      labels:
        service: ${SERVICE}
    spec:
      runtimeClassName: gvisor
      nodeSelector:
        cloud.google.com/gke-nodepool: apps

      volumes:
      - name: ${NGINX_VOLUME}
        configMap:
          name: ${NGINX_CONFIG}
      - name: ${SERVICE_VOLUME}
        persistentVolumeClaim:
          claimName: ${SERVICE_VOLUME}

      containers:
      - name: nginx
        image: nginx
        ports:
        - name: ${HTTP_PORT}
          containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: ${HTTP_PORT}
          timeoutSeconds: 10
        volumeMounts:
        - name: ${NGINX_VOLUME}
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          readOnly: true
        resources:
          requests:
            memory: 315M

      - name: neo4j
        image: neo4j:3.5
        command: ['sh', '-c']
        args:
        - |
          cat <<EOF >> conf/neo4j.conf
          dbms.connector.bolt.advertised_address=${DNS_HOSTNAME}:443
          dbms.logs.debug.path=/dev/stdout
          dbms.logs.http.path=/dev/stdout
          dbms.logs.query.path=/dev/stdout
          dbms.logs.security.path=/dev/stdout
          dbms.logs.user.path=/dev/stdout
          EOF
          exec /docker-entrypoint.sh neo4j
        env:
        - name: NEO4J_AUTH
          value: ${NEO4J_USERNAME}/$(NEO4J_PASSWORD)
        envFrom:
        - secretRef:
            name: ${SERVICE_SECRET}
        ports:
        - name: ${BOLT_PORT}
          containerPort: 7687
        readinessProbe:
          tcpSocket:
            port: ${BOLT_PORT}
          timeoutSeconds: 10
          initialDelaySeconds: 15
        volumeMounts:
        - name: ${SERVICE_VOLUME}
          mountPath: /data
        resources:
          requests:
            memory: 315M
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cartography
  namespace: ${NAMESPACE}
spec:
  schedule: "0 4 * * *" # daily at 4am UTC
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 0
      template:
        spec:
          serviceAccountName: ${K8S_SERVICE_ACCOUNT}
          runtimeClassName: gvisor
          restartPolicy: OnFailure
          nodeSelector:
            cloud.google.com/gke-nodepool: batch

          containers:
          - name: cartography
            image: ${CARTOGRAPHY_IMAGE}
            envFrom:
            - secretRef:
                name: ${SERVICE_SECRET}
            args: [
              '--neo4j-uri', 'bolt://${SERVICE}:7687',
              '--neo4j-user', '${NEO4J_USERNAME}',
              '--neo4j-password-env-var', 'NEO4J_PASSWORD',
            ]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${K8S_SERVICE_ACCOUNT}
  namespace: ${NAMESPACE}
  annotations:
    iam.gke.io/gcp-service-account: ${GCP_SERVICE_ACCOUNT_EMAIL}
