apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeAddress
metadata:
  name: ${IP_NAME}
spec:
  location: global
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${DEPLOYMENT}
spec:
  replicas: 2
  selector:
    matchLabels:
      deployment: ${DEPLOYMENT}
  template:
    metadata:
      labels:
        deployment: ${DEPLOYMENT}
    spec:
      runtimeClassName: gvisor

      containers:
      - name: sdarq-frontend
        image: gcr.io/dsp-appsec-infra-prod/sdarq-frontend
        ports:
        - name: ${TARGET_PORT}
          containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: ${TARGET_PORT}

      - name: sdarq-backend
        image: gcr.io/dsp-appsec-infra-prod/sdarq-backend
        ports:
        - name: ${TARGET_PORT}
          containerPort: 8080
        envFrom:
          - secretRef:
              name: ${SDARQ_SECRET}