apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${DEPLOYMENT}
  namespace: ${NAMESPACE}
spec:
  selector:
    matchLabels:
      service: ${SERVICE}
  template:
    metadata:
      labels:
        service: ${SERVICE}
    spec:
      runtimeClassName: gvisor

      containers:
      - name: frontend
        image: ${SDARQ_FRONTEND_IMAGE}
        ports:
        - name: ${FRONTEND_PORT}
          containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: ${FRONTEND_PORT}
          timeoutSeconds: 10

      - name: backend
        image: ${SDARQ_BACKEND_IMAGE}
        ports:
        - name: ${BACKEND_PORT}
          containerPort: 8080
        envFrom:
        - secretRef:
            name: ${SDARQ_SECRET}
        - configMapRef:
            name: ${SDARQ_CONFIG}
        readinessProbe:
          httpGet:
            path: /health/
            port: ${BACKEND_PORT}
          timeoutSeconds: 10
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${SDARQ_CONFIG}
  namespace: ${NAMESPACE}
data:
  dojo_host: http://${DOJO_SERVICE}.${DOJO_NAMESPACE}/
  sdarq_host: https://${DNS_HOSTNAME}
