apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${DEPLOYMENT}
  namespace: ${NAMESPACE}
spec:
  selector:
    matchLabels:
      deployment: ${DEPLOYMENT}
  template:
    metadata:
      labels:
        deployment: ${DEPLOYMENT}
    spec:
      runtimeClassName: gvisor

      containers:
      - name: sdarq-frontend
        image: ${SDARQ_FRONTEND_IMAGE}
        ports:
        - name: ${FRONTEND_PORT}
          containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: ${FRONTEND_PORT}

      - name: sdarq-backend
        image: ${SDARQ_BACKEND_IMAGE}
        ports:
        - name: ${BACKEND_PORT}
          containerPort: 8080
        envFrom:
        - secretRef:
            name: ${SDARQ_SECRET}
        - configMapRef:
            name: ${SDARQ_CONFIG}
        readinessProbe:
          httpGet:
            path: /health/
            port: ${BACKEND_PORT}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${SDARQ_CONFIG}
  namespace: ${NAMESPACE}
data:
  sdarq_host: https://${DNS_HOSTNAME}
