FROM defectdojo/defectdojo-django as dd


FROM dd as patch

USER root

WORKDIR /

COPY django.patch .

RUN git apply django.patch


FROM dd

COPY --from=patch /entrypoint-initializer.sh /entrypoint-initializer.sh
