FROM defectdojo/defectdojo-nginx AS nginx


FROM alpine AS patch

COPY --from=nginx /etc/nginx/nginx.conf .
COPY nginx.patch .

RUN apk add patch && patch -p1 < nginx.patch


FROM nginx

COPY --from=patch nginx.conf /etc/nginx/
