FROM defectdojo/defectdojo-django:2.43.4 as dd

FROM dd as patch

USER root

WORKDIR /

COPY django.patch .

RUN git apply -v django.patch

FROM dd

COPY --from=patch /entrypoint-initializer.sh /entrypoint-initializer.sh
