apiVersion: core.cnrm.cloud.google.com/v1beta1
kind: ConfigConnector
metadata:
  # the name is restricted to ensure that there is only ConfigConnector instance installed in your cluster
  name: configconnector.core.cnrm.cloud.google.com
