---
apiVersion: core.cnrm.cloud.google.com/v1beta1
kind: ConfigConnectorContext
metadata:
  name: configconnectorcontext.core.cnrm.cloud.google.com
  namespace: ${NAMESPACE}
spec:
  googleServiceAccount: ${cnrm_sa}
  stateIntoSpec: Absent
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: cnrm-${NAMESPACE}
  namespace: ${GLOBAL_NAMESPACE}
spec:
  member: serviceAccount:${PROJECT_ID}.svc.id.goog[cnrm-system/cnrm-controller-manager-${NAMESPACE}]
  role: roles/iam.workloadIdentityUser
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    external: projects/${PROJECT_ID}/serviceAccounts/${cnrm_sa}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cnrm-viewer-${NAMESPACE}
  namespace: ${GLOBAL_NAMESPACE}
rules:
- apiGroups:
  - dns.cnrm.cloud.google.com
  resources:
  - '*'
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cnrm-${NAMESPACE}-dnsmanagedzone
  namespace: ${GLOBAL_NAMESPACE}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cnrm-viewer-${NAMESPACE}
subjects:
- kind: ServiceAccount
  name: cnrm-controller-manager-${NAMESPACE}
  namespace: cnrm-system
