apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeDisk
metadata:
  name: ${COMPUTE_DISK}
  namespace: ${NAMESPACE}
  annotations:
    cnrm.cloud.google.com/deletion-policy: abandon
spec:
  location: ${REGION}
  replicaZones:
  - ${ZONE_1}
  - ${ZONE_2}
  resourcePolicies:
  - name: ${DISK_SNAPSHOT_POLICY}
    namespace: ${GLOBAL_NAMESPACE}