apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeDisk
metadata:
  name: ${SERVICE_DISK}
  namespace: ${NAMESPACE}
  annotations:
    cnrm.cloud.google.com/deletion-policy: abandon
spec:
  location: ${REGION}
  replicaZones:
  - https://www.googleapis.com/compute/v1/projects/${PROJECT_ID}/zones/${ZONE_1}
  - https://www.googleapis.com/compute/v1/projects/${PROJECT_ID}/zones/${ZONE_2}
  resourcePolicies:
  - name: ${DISK_SNAPSHOT_POLICY}
    namespace: ${GLOBAL_NAMESPACE}
  size: 200
  interface: '' # workaround for https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/521
