apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSRecordSet
metadata:
  name: ${HOST}
spec:
  name: ${DNS_HOSTNAME}.
  type: A
  ttl: 300
  managedZoneRef:
    name: ${DNS_ZONE}
    namespace: ${NAMESPACE}
  rrdatas:
  - ${IP_ADDRESS}
