apiVersion: autoscaling.apiserver.k8s.io/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa
  namespace: ${NAMESPACE}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ${NAMESPACE}
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80