apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ${INGRESS}
  namespace: ${NAMESPACE}
  annotations:
    kubernetes.io/ingress.global-static-ip-name: ${IP_NAME}
    networking.gke.io/managed-certificates: ${MANAGED_CERT}
    networking.gke.io/v1beta1.FrontendConfig: ${FRONTEND_CONFIG}
spec:
  rules:
  - host: ${DNS_HOSTNAME}
    http:
      paths:
      - backend:
          serviceName: ${SERVICE}
          servicePort: ${SERVICE_PORT}
---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: ${FRONTEND_CONFIG}
spec:
  redirectToHttps:
    enabled: true
---
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: ${BACKEND_CONFIG}
  namespace: ${NAMESPACE}
spec:
  securityPolicy:
    name: ${BROAD_INGRESS_CSP}
---
apiVersion: v1
kind: Service
metadata:
  name: ${SERVICE}
  namespace: ${NAMESPACE}
  annotations:
    cloud.google.com/neg: |
      {
        "ingress": true
      }
    beta.cloud.google.com/backend-config: |
      {
        "ports": {
          "${SERVICE_PORT}": "${BACKEND_CONFIG}"
        }
      }
spec:
  type: NodePort
  selector:
    service: ${SERVICE}
  ports:
  - name: ${SERVICE_PORT}
    port: 80
    targetPort: ${TARGET_PORT}
