---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ${INGRESS}
  namespace: ${NAMESPACE}
  annotations:
    kubernetes.io/ingress.allow-http: 'false'
    kubernetes.io/ingress.global-static-ip-name: ${IP_NAME}
    networking.gke.io/managed-certificates: ${MANAGED_CERT}
spec:
  backend:
    serviceName: ${SERVICE}
    servicePort: http
---
apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: ${MANAGED_CERT}
  namespace: ${NAMESPACE}
spec:
  domains:
  - ${DNS_HOSTNAME}
---
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: ${BACKEND_CONFIG}
  namespace: ${NAMESPACE}
spec:
  securityPolicy:
    name: ${BROAD_INGRESS_CSP}
---
apiVersion: v1
kind: Service
metadata:
  name: ${SERVICE}
  namespace: ${NAMESPACE}
  annotations:
    cloud.google.com/neg: |
      {
        "ingress": true
      }
    beta.cloud.google.com/backend-config: |
      {
        "ports": {
          "${SERVICE_PORT}": "${BACKEND_CONFIG}"
        }
      }
spec:
  type: NodePort
  selector:
    deployment: ${DEPLOYMENT}
  ports:
  - name: ${SERVICE_PORT}
    port: 80
    targetPort: ${TARGET_PORT}
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: ${SERVICE}
  namespace: ${NAMESPACE}
spec:
  targetRef:
    apiVersion: apps/v1
    kind:       Deployment
    name:       ${DEPLOYMENT}
  updatePolicy:
    updateMode: Auto
