apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ${PSP_ROLE}
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs: ['use']
  resourceNames: ['${PSP_NAME}']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ${PSP_BINDING}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ${PSP_ROLE}
subjects:
# Authorize all service accounts in a namespace (recommended):
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts
