apiVersion: v1
kind: Service
metadata:
  name: ${DEPLOYMENT}
  annotations:
    cloud.google.com/neg: |
      {
        "ingress": true
      }
    beta.cloud.google.com/backend-config: |
      {
        "ports": {
          "80": "${DEPLOYMENT}-backend"
        }
      }
spec:
  type: NodePort
  selector:
    deployment: ${DEPLOYMENT}
  ports:
  - port: 80
    targetPort: ${TARGET_PORT}
---
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: ${DEPLOYMENT}-backend
spec:
  securityPolicy:
    name: ${BROAD_INGRESS_CSP}
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: ${DEPLOYMENT}-vpa
spec:
  targetRef:
    apiVersion: apps/v1
    kind:       Deployment
    name:       ${DEPLOYMENT}
  updatePolicy:
    updateMode: Auto
