apiVersion: v1
kind: PersistentVolume
metadata:
  name: ${SERVICE_VOLUME}
  namespace: ${NAMESPACE}
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 200
  gcePersistentDisk:
    pdName: ${SERVICE_DISK}
  claimRef:
    name: ${SERVICE_VOLUME}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${SERVICE_VOLUME}
  namespace: ${NAMESPACE}
spec:
  storageClassName: ''
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200
