apiVersion: v1
kind: PersistentVolume
metadata:
  name: ${SERVICE_VOLUME}
  namespace: ${NAMESPACE}
  labels:
    failure-domain.beta.kubernetes.io/zone: ${ZONE_1}__${ZONE_2}
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 200Gi
  gcePersistentDisk:
    pdName: ${SERVICE_DISK}
