apiVersion: v1
kind: PersistentVolume
metadata:
  name: ${SERVICE_VOLUME}
  namespace: ${NAMESPACE}
spec:
  storageClassName: ${REGIONAL_PD_CLASS}
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 200Gi
  gcePersistentDisk:
    pdName: ${SERVICE_DISK}
