FROM node:latest as node
WORKDIR /app/website
COPY src/base/. .
COPY docusaurus.config.js .
$list
RUN yarn install
RUN npm run build

FROM nginx:alpine
COPY --from=node /app/website/build/ /usr/share/nginx/html/