apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ${INGRESS}
  namespace: ${NAMESPACE}
  annotations:
    kubernetes.io/ingress.allow-http: 'false'
    kubernetes.io/ingress.global-static-ip-name: ${IP_NAME}
    networking.gke.io/managed-certificates: ${MANAGED_CERT}
spec:
  rules:
  - host: ${DNS_HOSTNAME}
    http:
      paths:
      - backend:
          serviceName: ${SERVICE}
          servicePort: ${SERVICE_PORT}

---
apiVersion: v1
kind: Service
metadata:
  name: ${SERVICE}
  namespace: ${NAMESPACE}
  annotations:
    cloud.google.com/neg: |
      {
        "ingress": true
      }
spec:
  type: NodePort
  selector:
    service: ${SERVICE}
  ports:
  - name: ${SERVICE_PORT}
    port: 80
    targetPort: ${TARGET_PORT}
