---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${JOB_CONFIG_MAP}
  namespace: ${NAMESPACE}
data:
  spec: |
    template:
      spec:
        serviceAccountName: ${JOB_SERVICE_ACCOUNT}
        runtimeClassName: gvisor
        restartPolicy: Never
        volumes:
        - name: shared-data
          emptyDir: {}
        nodeSelector:
          cloud.google.com/gke-nodepool: batch

        containers:
        - name: zap
          image: softwaresecurityproject/zap-stable
          volumeMounts:
            - name: shared-data
              mountPath: ${VOLUME_SHARE}
          command: ['zap.sh']
          env:
          - name: ZAP_API_KEY
            valueFrom:
              secretKeyRef:
                name: ${JOB_SECRET}
                key: ZAP_API_KEY
          args: [
            '-daemon',
            '-host', '127.0.0.1',
            '-port', '${ZAP_PORT}',
            '-config', 'api.key=$(ZAP_API_KEY)',
            '-config', 'api.filexfer=true',
            '-Xmx10g',
          ]
          resources:
            requests:
              memory: 10Gi
          

        - name: zap-scan
          image: ${ZAP_IMAGE}
          volumeMounts:
            - name: shared-data
              mountPath: ${VOLUME_SHARE}
          imagePullPolicy: Always
          args: ['scan']
          env:
          - name: CODEDX_URL
            value: ${CODEDX_URL}
          - name: BUCKET_NAME
            value: ${BUCKET_NAME}
          - name: SESSION_BUCKET
            value: ${SESSION_BUCKET}
          - name: VOLUME_SHARE
            value: ${VOLUME_SHARE}
          - name: ZAP_PORT
            value: '${ZAP_PORT}'
          - name: DEFECT_DOJO_URL
            value: ${DEFECT_DOJO_URL}
          - name: CODEDX_API_KEY
            valueFrom:
              secretKeyRef:
                name: ${JOB_SECRET}
                key: CODEDX_API_KEY
          - name: DEFECT_DOJO_KEY
            valueFrom:
              secretKeyRef:
                name: ${JOB_SECRET}
                key: DEFECT_DOJO_KEY
          - name: DEFECT_DOJO_USER
            valueFrom:
              secretKeyRef:
                name: ${JOB_SECRET}
                key: DEFECT_DOJO_USER
          - name: ZAP_API_KEY
            valueFrom:
              secretKeyRef:
                name: ${JOB_SECRET}
                key: ZAP_API_KEY
          - name: DEFECT_DOJO
            valueFrom:
              secretKeyRef:
                name: ${JOB_SECRET}
                key: DEFECT_DOJO
          - name: DRIVE_ROOT_ID
            valueFrom:
              secretKeyRef:
                name: ${JOB_SECRET}
                key: DRIVE_ROOT_ID
          - name: DRIVE_ID
            valueFrom:
              secretKeyRef:
                name: ${JOB_SECRET}
                key: DRIVE_ID
          - name: SLACK_TOKEN
            valueFrom:
              secretKeyRef:
                name: ${JOB_SECRET}
                key: SLACK_TOKEN
          - name: CODEDX_PROJECT
            valueFrom:
              fieldRef:
                fieldPath: metadata.annotations['CODEDX_PROJECT']
          - name: URL
            valueFrom:
              fieldRef:
                fieldPath: metadata.annotations['URL']
          - name: SCAN_TYPE
            valueFrom:
              fieldRef:
                fieldPath: metadata.annotations['SCAN_TYPE']
          - name: SLACK_CHANNEL
            valueFrom:
              fieldRef:
                fieldPath: metadata.annotations['SLACK_CHANNEL']
          - name: PRODUCT_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.annotations['PRODUCT_ID']
          - name: SEVERITIES
            valueFrom:
              fieldRef:
                fieldPath: metadata.annotations['SEVERITIES']
          resources:
            requests:
              memory: 50Mi
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicy
metadata:
  name: ${JOB_TOPIC}-policy
  namespace: ${NAMESPACE}
spec:
  resourceRef:
    apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
    kind: PubSubTopic
    name: ${JOB_TOPIC}
  bindings:
  - role: roles/pubsub.publisher
    members:
    - serviceAccount:${SDARQ_SERVICE_ACCOUNT}@${PROJECT_ID}.iam.gserviceaccount.com
    - serviceAccount:${CRON_SERVICE_ACCOUNT}@${PROJECT_ID}.iam.gserviceaccount.com
---
apiVersion: v1
kind: List
items:
- &cron-job
  apiVersion: batch/v1
  kind: CronJob
  metadata:
    name: ${CRON_JOB}-weekly
    namespace: ${NAMESPACE}
  spec:
    schedule: "0 7 * * 4"
    jobTemplate:
      spec:
        template:
          spec: &cron-job-spec
            serviceAccountName: ${CRON_SERVICE_ACCOUNT}
            runtimeClassName: gvisor
            nodeSelector:
              cloud.google.com/gke-nodepool: batch
            restartPolicy: OnFailure

            containers:
            - &cron-job-container
              name: zap-trigger
              image: ${ZAP_IMAGE}
              args: ['trigger', '-s', 'auth', 'ui']
              env:
              - name: GCP_PROJECT_ID
                value: ${PROJECT_ID}
              - name: ZAP_TOPIC_NAME
                value: ${JOB_TOPIC}
              - name: DEFECT_DOJO_URL
                value: ${DEFECT_DOJO_URL}
              - name: DEFECT_DOJO_KEY
                valueFrom:
                  secretKeyRef:
                    name: ${JOB_SECRET}
                    key: DEFECT_DOJO_KEY
              - name: DEFECT_DOJO
                valueFrom:
                  secretKeyRef:
                    name: ${JOB_SECRET}
                    key: DEFECT_DOJO
              resources:
                requests:
                  memory: 50Mi
- << : *cron-job
  metadata:
    name: ${CRON_JOB}-monthly
    namespace: ${NAMESPACE}
  spec:
    schedule: "0 0 1 * *"
    jobTemplate:
      spec:
        template:
          spec:
            << : *cron-job-spec
            containers:
            - << : *cron-job-container
              args: ['trigger', '-s', 'api']

---
apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucket
metadata:
  name: ${BUCKET_NAME}
  namespace: ${NAMESPACE}
  annotations:
    cnrm.cloud.google.com/deletion-policy: abandon
spec:
  uniformBucketLevelAccess: true
  versioning:
    enabled: true
---
apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucket
metadata:
  name: ${SESSION_BUCKET}
  namespace: ${NAMESPACE}
spec:
  uniformBucketLevelAccess: true
  versioning:
    enabled: false
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: ${BUCKET_NAME}-policy
  namespace: ${NAMESPACE}
spec:
  member: serviceAccount:${JOB_SERVICE_ACCOUNT}@${PROJECT_ID}.iam.gserviceaccount.com
  role: roles/storage.objectAdmin
  resourceRef:
    apiVersion: storage.cnrm.cloud.google.com/v1beta1
    kind: StorageBucket
    name: ${BUCKET_NAME}
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: ${SESSION_BUCKET}-policy
  namespace: ${NAMESPACE}
spec:
  member: serviceAccount:${JOB_SERVICE_ACCOUNT}@${PROJECT_ID}.iam.gserviceaccount.com
  role: roles/storage.objectAdmin
  resourceRef:
    apiVersion: storage.cnrm.cloud.google.com/v1beta1
    kind: StorageBucket
    name: ${SESSION_BUCKET}