apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: zap
  namespace: ${NAMESPACE}
spec:
  schedule: "0 4 * * 0"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 3600
      template:
        spec:
          runtimeClassName: gvisor
          nodeSelector:
            cloud.google.com/gke-nodepool: batch
          restartPolicy: Never
          containers:
          - name: zap
            image: owasp/zap2docker-weekly
            command: ["/bin/sh", "-c"]
            args: ["zap-cli quick-scan -sc -o '-config api.disablekey=true' -s xss https://app.terra.bio"]
