---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${JOB_CONFIG_MAP}
  namespace: ${NAMESPACE}
data:
  spec: |
    template:
      spec:
        serviceAccountName: ${K8S_SERVICE_ACCOUNT}
        runtimeClassName: gvisor
        restartPolicy: OnFailure
        nodeSelector:
          cloud.google.com/gke-nodepool: batch
        containers:
        - name: zap-scan
          image: ${ZAP_IMAGE}
          imagePullPolicy: Always
          env:
          - name: CODEDX_URL
            value: ${CODEDX_URL}
          - name: ZAP_PORT
            value: ${ZAP_PORT}
          - name: CODEDX_API_KEY
            valueFrom:
              secretKeyRef:
                name: ${JOB_SECRET}
                key: CODEDX_API_KEY
          - name: SLACK_WEBHOOK
            valueFrom:
              secretKeyRef:
                name: ${JOB_SECRET}
                key: SLACK_WEBHOOK
          - name: CODEDX_PROJECT
            valueFrom:
              fieldRef:
                fieldPath: metadata.annotations['CODEDX_PROJECT']
          - name: URL
            valueFrom:
              fieldRef:
                fieldPath: metadata.annotations['URL']
          - name: SCAN_TYPE
            valueFrom:
              fieldRef:
                fieldPath: metadata.annotations['SCAN_TYPE']
          resources:
            requests:
              memory: 2Gi
        - name: zap
          image: owasp/zap2docker-weekly
          command: ['zap.sh']
          args: ['-daemon', 
            '-host', '0.0.0.0', 
            '-port', '$(ZAP_PORT)',
            '-config', 'api.disablekey=true',
            '-config', 'api.addrs.addr.name=.*',
            '-config', 'api.addrs.addr.regex=true']
          env:
          - name: ZAP_PORT
            value: ${ZAP_PORT}
        resources:
          requests:
            memory: 2Gi
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicy
metadata:
  name: ${JOB_TOPIC}-policy
  namespace: ${NAMESPACE}
spec:
  resourceRef:
    apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
    kind: PubSubTopic
    name: ${JOB_TOPIC}
  bindings:
  - role: roles/pubsub.publisher
    members:
    - serviceAccount:${K8S_SERVICE_ACCOUNT}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: automated-zap-scan-trigger-cronjob
  namespace: ${NAMESPACE}
spec:
  schedule: "0 7 * * 0"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: ${K8S_SERVICE_ACCOUNT}
          runtimeClassName: gvisor
          nodeSelector:
            cloud.google.com/gke-nodepool: batch
          restartPolicy: OnFailure
          containers:
          - name: zap-trigger
            image: ${ZAP_IMAGE}
            command: ['python3', '/weekly_trigger.py']
            env:
              - name: GCP_PROJECT_ID
                value: ${PROJECT_ID}
              - name: ZAP_TOPIC_NAME
                value: ${JOB_TOPIC}
              - name: DEFECT_DOJO_URL
                value: ${DEFECT_DOJO_URL}
              - name: DEFECT_DOJO_KEY
                valueFrom:
                  secretKeyRef:
                    name: ${JOB_SECRET}
                    key: DEFECT_DOJO_KEY
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: automated-monthly-zap-scan-trigger-cronjob
  namespace: ${NAMESPACE}
spec:
  schedule: "0 0 1 * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: ${K8S_SERVICE_ACCOUNT}
          runtimeClassName: gvisor
          nodeSelector:
            cloud.google.com/gke-nodepool: batch
          restartPolicy: OnFailure
          containers:
          - name: zap-trigger-monthly
            image: ${ZAP_IMAGE}
            command: ['python3', '/trigger.py', 'ui-scan']
            env:
              - name: GCP_PROJECT_ID
                value: ${PROJECT_ID}
              - name: ZAP_TOPIC_NAME
                value: ${JOB_TOPIC}
              - name: DEFECT_DOJO_URL
                value: ${DEFECT_DOJO_URL}
              - name: DEFECT_DOJO_KEY
                valueFrom:
                  secretKeyRef:
                    name: ${JOB_SECRET}
                    key: DEFECT_DOJO_KEY
