# This workflow will publish docs to github pages
# https://broadinstitute.github.io/dsp-appsec-infrastructure-apps/

name: Deploy docs to Github Pages

on:
  push:
   branches:
     - master
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: docs/src/website
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-website-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-website-

      - run: yarn install --frozen-lockfile
      - run: yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./docs/src/website/build/dsp-appsec-infrastructure-apps
