# This workflow will publish docs to github pages
# https://broadinstitute.github.io/dsp-appsec-infrastructure-apps/

name: Deploy docs to Github Pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: SSH client
      uses: webfactory/ssh-agent@v0.2.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}
    - run: git config --global user.email "appsec@users.noreply.github.com"
    - run: git config --global user.name "appsec@broadinstitute.org"
    - run: ls -al && cd docs/src/website && yarn install && GIT_USER=appsec@broadinstitute.org USE_SSH=true yarn run publish-gh-pages
